### ISSUE TITLE
Metrics are not collected 

### ISSUE THREAD

**Issue by themkarimi** [Lightstreamer/Lightstreamer-utility-MetricsExporter-Adapter#1]
Hi,

I have installed the metrics exporter on my Lightsreamer instance but nothing is collected and I receive this error message.:

2022-03-08 12:38:10,602 WARN c.l.u.m.j.JMXMetricsCollector [Thread-21] Error while querying mbeans
java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy26.getStatus(Unknown Source) ~[?:?]
	at com.lightstreamer.utility.metrics.jmx.JMXMetricsCollector.lambda$inititalize$4(JMXMetricsCollector.java:326) ~[lightstreamer-utility-metricsexporter-adapter-0.1.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: javax.management.AttributeNotFoundException: No such attribute: Status
	at com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:81) ~[?:?]
	at com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206) ~[?:?]
	at javax.management.StandardMBean.getAttribute(StandardMBean.java:372) ~[?:?]

I am using the latest verison of Lightstreamer docker image:[7.2.2](https://hub.docker.com/layers/lightstreamer/library/lightstreamer/7.2.2/images/sha256-22019192efde670f72caba493bd2005e1629bca0b400cd2f38b642bbb7dca402?context=explore)

**Comment by Bravo27** [comment]
Hi Mojtaba Karimi,

It seems that your Lightstreamer license does not support the full JMX interface feature; or it is disabled through configuration.
Please could you check in the 'License' tab of the Monitoring Dashboard if the 'JMX Management API' feature is enabled?

However, I believe that the message is not completely clear as to the reasons for the error; I think a change is needed to provide a more specific message.

Thank you,
Giuseppe

**Comment by themkarimi** [comment]
> Hi Mojtaba Karimi,
> 
> It seems that your Lightstreamer license does not support the full JMX interface feature; or it is disabled through configuration. Please could you check in the 'License' tab of the Monitoring Dashboard if the 'JMX Management API' feature is enabled?
> 
> However, I believe that the message is not completely clear as to the reasons for the error; I think a change is needed to provide a more specific message.
> 
> Thank you, Giuseppe

Hello Giuseppe,
Thanks for your response. you were right despite the fact that we are using the enterprise license, this feature is disabled. is there any way to enable it?

**Comment by Bravo27** [comment]
> > Hi Mojtaba Karimi,
> > It seems that your Lightstreamer license does not support the full JMX interface feature; or it is disabled through configuration. Please could you check in the 'License' tab of the Monitoring Dashboard if the 'JMX Management API' feature is enabled?
> > However, I believe that the message is not completely clear as to the reasons for the error; I think a change is needed to provide a more specific message.
> > Thank you, Giuseppe
> 
> Hello Giuseppe, Thanks for your response. you were right despite the fact that we are using the enterprise license, this feature is disabled. is there any way to enable it?

The 'JMX Management API' is an optional feature and can be enabled or not based on the list of features included in the enterprise license purchased. If not, a license upgrade will be required.

However, if you are interested in testing the export of the Lightstreamer server metrics to prometheus, you can use a test server running the DEMO license type.

**Comment by themkarimi** [comment]
> > > Hi Mojtaba Karimi,
> > > It seems that your Lightstreamer license does not support the full JMX interface feature; or it is disabled through configuration. Please could you check in the 'License' tab of the Monitoring Dashboard if the 'JMX Management API' feature is enabled?
> > > However, I believe that the message is not completely clear as to the reasons for the error; I think a change is needed to provide a more specific message.
> > > Thank you, Giuseppe
> > 
> > 
> > Hello Giuseppe, Thanks for your response. you were right despite the fact that we are using the enterprise license, this feature is disabled. is there any way to enable it?
> 
> The 'JMX Management API' is an optional feature and can be enabled or not based on the list of features included in the enterprise license purchased. If not, a license upgrade will be required.
> 
> However, if you are interested in testing the export of the Lightstreamer server metrics to prometheus, you can use a test server running the DEMO license type.

Our production license is expiring soon so we might try to add this feature in our next purchase.
