### ISSUE TITLE
Feature Request: Adding an option to change log level(Too Many Logs)

### ISSUE THREAD

**Issue by themkarimi** [Lightstreamer/Lightstreamer-utility-MetricsExporter-Adapter#2]
Hello,

I have installed this adapter in my production environment but it generates too many debug messages, is there anyway to make its log level to error or something? my lightstreamer log level is currently at WARN and is logging fine.

Thanks!

**Comment by Bravo27** [comment]
Hi themkarimi,

In the folder metrics_exporter\classes\ there is the file with name _'log4j2.xml'_ where you can configure the log settings as per your preferences. 

For example to change level from debug to warn change as below:

<Logger name="export_jmx_metrics" **level="warn"** additivity="false">
<AppenderRef ref="STDOUT"/>
<AppenderRef ref="File"/>
</Logger>

Please let us know if you need any further clarifications.

Regards,
Giuseppe

**Comment by Bravo27** [comment]
Hi themkarimi,

Were you then able to configure the log settings using the suggested file?

Can I consider this issue closed?

Thanks,
Giuseppe

**Comment by themkarimi** [comment]
Hi, 
Thanks for your help. I was able to configure log level successfully. You can close this issue.
Thanks

**Comment by Bravo27** [comment]
Thank you for the feedback.
